qpOASES: src/BLASReplacement.cpp File Reference
BLASReplacement.cpp File Reference
#include <qpOASES/Utils.hpp>
Functions
void dgemm_ (const char *TRANSA, const char *TRANSB, const unsigned long *M, const unsigned long *N, const unsigned long *K, const double *ALPHA, const double *A, const unsigned long *LDA, const double *B, const unsigned long *LDB, const double *BETA, double *C, const unsigned long *LDC)
void sgemm_ (const char *TRANSA, const char *TRANSB, const unsigned long *M, const unsigned long *N, const unsigned long *K, const float *ALPHA, const float *A, const unsigned long *LDA, const float *B, const unsigned long *LDB, const float *BETA, float *C, const unsigned long *LDC)
Detailed Description
Author
Hans Joachim Ferreau, Andreas Potschka, Christian Kirches
Version
3.2
Date
2007-2015
BLAS Level 3 replacement routines.
Function Documentation
dgemm_()
void dgemm_ (const char * , const char * , const unsigned long * , const unsigned long * , const unsigned long * , const double * , const double * , const unsigned long * , const double * , const unsigned long * , const double * , double * , const unsigned long *)
Performs one of the matrix-matrix operation in double precision.
References BT_FALSE, BT_TRUE, isEqual(), isZero(), and REFER_NAMESPACE_QPOASES.
sgemm_()
void sgemm_ (const char * , const char * , const unsigned long * , const unsigned long * , const unsigned long * , const float * , const float * , const unsigned long * , const float * , const unsigned long * , const float * , float * , const unsigned long *)
Performs one of the matrix-matrix operation in single precision.
References BT_FALSE, BT_TRUE, isEqual(), isZero(), and REFER_NAMESPACE_QPOASES.