qpOASES: examples/example1.cpp File Reference
example1.cpp File Reference
#include <qpOASES.hpp>
Functions
int main ()
Detailed Description
Author
Hans Joachim Ferreau
Version
3.2
Date
2007-2015
Very simple example for testing qpOASES using the QProblem class.
Function Documentation
main()
int main ()
Example for qpOASES main function using the QProblem class.
References QProblem::getDualSolution(), QProblemB::getObjVal(), QProblemB::getPrimalSolution(), QProblem::hotstart(), QProblem::init(), QProblemB::printOptions(), real_t, QProblemB::setOptions(), and USING_NAMESPACE_QPOASES.